[env]
RUST_BACKTRACE = "1"
RUST_LOG = "debug"
ANCHOR_WALLET = "C:\\Users\\Abrham Wendmeneh\\.config\\solana\\id.json"

[build]
target = "x86_64-pc-windows-msvc"
target-dir = "C:\\Users\\Abrham Wendmeneh\\AppData\\Local\\Temp\\solana-build"

[target.x86_64-pc-windows-msvc]
rustflags = ["-C", "link-arg=/STACK:4194304"]

[net]
git-fetch-with-cli = true 